// Generated by alkabi — do not edit.
export const FrBTCAbi = {
  "alkabi": 1,
  "contract": "SyntheticBitcoin",
  "types": {},
  "methods": [
    {
      "name": "initialize",
      "opcode": 0,
      "kind": "execute"
    },
    {
      "name": "setSigner",
      "opcode": 1,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "vout": "u128"
          }
        }
      }
    },
    {
      "name": "setPremium",
      "opcode": 4,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "premium": "u128"
          }
        }
      }
    },
    {
      "name": "wrap",
      "opcode": 77,
      "kind": "execute"
    },
    {
      "name": "unwrap",
      "opcode": 78,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "vout": "u128",
            "amount_requested": "u128"
          }
        }
      }
    },
    {
      "name": "getName",
      "opcode": 99,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "string"
      }
    },
    {
      "name": "getSymbol",
      "opcode": 100,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "string"
      }
    },
    {
      "name": "getPendingPayments",
      "opcode": 101,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": {
          "array": {
            "type": "u8"
          }
        }
      }
    },
    {
      "name": "getDecimals",
      "opcode": 102,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "u8"
      }
    },
    {
      "name": "getSigner",
      "opcode": 103,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": {
          "array": {
            "type": "u8"
          }
        }
      }
    },
    {
      "name": "getPremium",
      "opcode": 104,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "u128"
      }
    },
    {
      "name": "getTotalSupply",
      "opcode": 105,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "u128"
      }
    }
  ]
} as const;

export default FrBTCAbi;
