// Generated by alkabi — do not edit.
export const OylAMMPoolAbi = {
  "alkabi": 1,
  "contract": "AMMPool",
  "types": {
    "AlkaneId": {
      "struct": {
        "block": "u128",
        "tx": "u128"
      }
    }
  },
  "methods": [
    {
      "name": "initPool",
      "opcode": 0,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "alkane_a": {
              "$ref": "AlkaneId"
            },
            "alkane_b": {
              "$ref": "AlkaneId"
            },
            "factory": {
              "$ref": "AlkaneId"
            }
          }
        }
      }
    },
    {
      "name": "addLiquidity",
      "opcode": 1,
      "kind": "execute"
    },
    {
      "name": "burn",
      "opcode": 2,
      "kind": "execute"
    },
    {
      "name": "swap",
      "opcode": 3,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "amount_0_out": "u128",
            "amount_1_out": "u128",
            "to": {
              "$ref": "AlkaneId"
            },
            "data": {
              "array": {
                "type": "u128"
              }
            }
          }
        }
      }
    },
    {
      "name": "collectFees",
      "opcode": 10,
      "kind": "execute"
    },
    {
      "name": "getTotalFee",
      "opcode": 20,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "u128"
      }
    },
    {
      "name": "setTotalFee",
      "opcode": 21,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "total_fee_per_1000": "u128"
          }
        }
      }
    },
    {
      "name": "forwardIncoming",
      "opcode": 50,
      "kind": "execute"
    },
    {
      "name": "getReserves",
      "opcode": 97,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": {
          "struct": {
            "_0": "u128",
            "_1": "u128"
          }
        }
      }
    },
    {
      "name": "getPriceCumulativeLast",
      "opcode": 98,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": {
          "struct": {
            "_0": "u128",
            "_1": "u128"
          }
        }
      }
    },
    {
      "name": "getName",
      "opcode": 99,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "string"
      }
    },
    {
      "name": "poolDetails",
      "opcode": 999,
      "kind": "execute",
      "output": {
        "mode": "raw",
        "schema": {
          "array": {
            "type": "u8"
          }
        }
      }
    }
  ]
} as const;

export default OylAMMPoolAbi;
