// Generated by alkabi — do not edit.
export const OylAMMAbi = {
  "alkabi": 1,
  "contract": "AMMFactory",
  "types": {
    "AlkaneId": {
      "struct": {
        "block": "u128",
        "tx": "u128"
      }
    }
  },
  "methods": [
    {
      "name": "initFactory",
      "opcode": 0,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "pool_factory_id": "u128",
            "beacon_id": {
              "$ref": "AlkaneId"
            }
          }
        }
      }
    },
    {
      "name": "createNewPool",
      "opcode": 1,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "token_a": {
              "$ref": "AlkaneId"
            },
            "token_b": {
              "$ref": "AlkaneId"
            },
            "amount_a": "u128",
            "amount_b": "u128"
          }
        }
      }
    },
    {
      "name": "findExistingPoolId",
      "opcode": 2,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "alkane_a": {
              "$ref": "AlkaneId"
            },
            "alkane_b": {
              "$ref": "AlkaneId"
            }
          }
        }
      }
    },
    {
      "name": "getAllPools",
      "opcode": 3,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": {
          "array": {
            "type": "u8"
          }
        }
      }
    },
    {
      "name": "getNumPools",
      "opcode": 4,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": {
          "array": {
            "type": "u8"
          }
        }
      }
    },
    {
      "name": "setPoolFactoryId",
      "opcode": 7,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "pool_factory_id": "u128"
          }
        }
      }
    },
    {
      "name": "collectFees",
      "opcode": 10,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "pool_id": {
              "$ref": "AlkaneId"
            }
          }
        }
      }
    },
    {
      "name": "addLiquidity",
      "opcode": 11,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "token_a": {
              "$ref": "AlkaneId"
            },
            "token_b": {
              "$ref": "AlkaneId"
            },
            "amount_a_desired": "u128",
            "amount_b_desired": "u128",
            "amount_a_min": "u128",
            "amount_b_min": "u128",
            "deadline": "u128"
          }
        }
      }
    },
    {
      "name": "burn",
      "opcode": 12,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "token_a": {
              "$ref": "AlkaneId"
            },
            "token_b": {
              "$ref": "AlkaneId"
            },
            "liquidity": "u128",
            "amount_a_min": "u128",
            "amount_b_min": "u128",
            "deadline": "u128"
          }
        }
      }
    },
    {
      "name": "swapExactTokensForTokens",
      "opcode": 13,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "path": {
              "array": {
                "type": {
                  "$ref": "AlkaneId"
                }
              }
            },
            "amount_in": "u128",
            "amount_out_min": "u128",
            "deadline": "u128"
          }
        }
      }
    },
    {
      "name": "swapTokensForExactTokens",
      "opcode": 14,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "path": {
              "array": {
                "type": {
                  "$ref": "AlkaneId"
                }
              }
            },
            "amount_out": "u128",
            "amount_in_max": "u128",
            "deadline": "u128"
          }
        }
      }
    },
    {
      "name": "setTotalFeeForPool",
      "opcode": 21,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "pool_id": {
              "$ref": "AlkaneId"
            },
            "total_fee_per_1000": "u128"
          }
        }
      }
    },
    {
      "name": "swapExactTokensForTokensImplicit",
      "opcode": 29,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "path": {
              "array": {
                "type": {
                  "$ref": "AlkaneId"
                }
              }
            },
            "amount_out_min": "u128",
            "deadline": "u128"
          }
        }
      }
    },
    {
      "name": "forward",
      "opcode": 50,
      "kind": "execute"
    }
  ]
} as const;

export default OylAMMAbi;
