// Generated by alkabi — do not edit.
export const TokenAbi = {
  "alkabi": 1,
  "contract": "MintableAlkane",
  "types": {},
  "methods": [
    {
      "name": "initialize",
      "opcode": 0,
      "kind": "execute",
      "input": {
        "mode": "legacy",
        "schema": {
          "struct": {
            "token_units": "u128",
            "value_per_mint": "u128",
            "cap": "u128",
            "name_part1": "u128",
            "name_part2": "u128",
            "symbol": "u128"
          }
        }
      }
    },
    {
      "name": "mintTokens",
      "opcode": 77,
      "kind": "execute"
    },
    {
      "name": "getName",
      "opcode": 99,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "string"
      }
    },
    {
      "name": "getSymbol",
      "opcode": 100,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "string"
      }
    },
    {
      "name": "getTotalSupply",
      "opcode": 101,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "u128"
      }
    },
    {
      "name": "getCap",
      "opcode": 102,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "u128"
      }
    },
    {
      "name": "getMinted",
      "opcode": 103,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "u128"
      }
    },
    {
      "name": "getValuePerMint",
      "opcode": 104,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": "u128"
      }
    },
    {
      "name": "getData",
      "opcode": 1000,
      "kind": "view",
      "output": {
        "mode": "raw",
        "schema": {
          "array": {
            "type": "u8"
          }
        }
      }
    }
  ]
} as const;

export default TokenAbi;
